### ISSUE TITLE
Facing issue on windows while bringing up vagrant.

### ISSUE THREAD

**Issue by Janavi006** [cisco-sso/k8s-devkit#22]
Getting the following error when i run "vagrant up" on windows: "default: sudo: unable to execute /vagrant/ansible/main.sh: No such file or directory"

**Comment by dcwangmit01** [comment]
Hi @Janavi006,

This current project is now deprecated.  Please use the dockerized kubernetes development kit instead.  It's way better, and hopefully you'll find it useful.

https://github.com/cisco-sso/kdk

-dave
